class Event {
  int? id; // Nullable id, since it will be auto-generated by the database
  String name;
  String category;
  String status;

  Event({
    this.id, // id is optional
    required this.name,
    required this.category,
    required this.status,
  });

  // Factory constructor for creating an Event object from JSON
  factory Event.fromJson(Map<String, dynamic> json) {
    return Event(
      id: json['id'], // id could be null from JSON or database
      name: json['name'] ?? '',
      category: json['category'] ?? '',
      status: json['status'] ?? '',
    );
  }

  // Getter for id (if null, throw an exception)
  int get eventId {
    if (id != null) {
      return id!;
    } else {
      throw Exception("Event ID is null!");
    }
  }

  // Method to convert an Event object to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id, // id may be null initially but will be set once inserted in the database
      'name': name,
      'category': category,
      'status': status,
    };
  }

  // Optional: fromMap method for database operations
  static Event fromMap(Map<String, dynamic> map) {
    return Event(
      id: map['id'], // Expect the id to be in the map
      name: map['name'],
      category: map['category'],
      status: map['status'],
    );
  }
}
