// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBml9Vduoa5jMq2EK3MIA7KCeZD_ASPtXQ',
    appId: '1:544174840258:web:02b53787a0f2c5fa8e9e5b',
    messagingSenderId: '544174840258',
    projectId: 'ssnormandie',
    authDomain: 'ssnormandie.firebaseapp.com',
    storageBucket: 'ssnormandie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQALbSLJGundE8ZH_PrtB4ra9jYL-Ee6E',
    appId: '1:544174840258:android:62823d372e0f8b4c8e9e5b',
    messagingSenderId: '544174840258',
    projectId: 'ssnormandie',
    storageBucket: 'ssnormandie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3BtlU-P35JzQcT5Ytig5w3-iu7wlwvKM',
    appId: '1:544174840258:ios:fecb59503a1c3e598e9e5b',
    messagingSenderId: '544174840258',
    projectId: 'ssnormandie',
    storageBucket: 'ssnormandie.firebasestorage.app',
    iosBundleId: 'com.example.mbileprogrammingproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3BtlU-P35JzQcT5Ytig5w3-iu7wlwvKM',
    appId: '1:544174840258:ios:fecb59503a1c3e598e9e5b',
    messagingSenderId: '544174840258',
    projectId: 'ssnormandie',
    storageBucket: 'ssnormandie.firebasestorage.app',
    iosBundleId: 'com.example.mbileprogrammingproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBml9Vduoa5jMq2EK3MIA7KCeZD_ASPtXQ',
    appId: '1:544174840258:web:6b20fa81a50b92c38e9e5b',
    messagingSenderId: '544174840258',
    projectId: 'ssnormandie',
    authDomain: 'ssnormandie.firebaseapp.com',
    storageBucket: 'ssnormandie.firebasestorage.app',
  );
}
